C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/standard.vert -o %2/standard_vert.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/standard_shadow.vert -o %2/standard_shadow_vert.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/standard_shadow.frag -o %2/standard_shadow_frag.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/standard_instanced.vert -o %2/standard_instanced_vert.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/standard_instanced_shadow.vert -o %2/standard_instanced_shadow_vert.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/standard.frag -o %2/standard_frag.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/shadow_debug.vert -o %2/shadow_debug_vert.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/shadow_debug.frag -o %2/shadow_debug_frag.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/cull.comp -o %2/cull_comp.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/pp.vert -o %2/pp_vert.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/pp_color_inv.frag -o %2/pp_color_inv_frag.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/pp_flip.frag -o %2/pp_flip_frag.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/pp_blur.frag -o %2/pp_blur_frag.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/pp_fxaa.frag -o %2/pp_fxaa_frag.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/grass.vert -o %2/grass_vert.spv
C:/VulkanSDK/1.3.239.0/Bin/glslc.exe %1/grass.frag -o %2/grass_frag.spv