C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/standard.vert -o standard_vert.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/standard_shadow.vert -o standard_shadow_vert.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/standard_instanced.vert -o standard_instanced_vert.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/standard_instanced_shadow.vert -o standard_instanced_shadow_vert.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/standard.frag -o standard_frag.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/shadow_debug.vert -o shadow_debug_vert.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/shadow_debug.frag -o shadow_debug_frag.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/pp.vert -o pp_vert.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/pp_color_inv.frag -o pp_color_inv_frag.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/pp_flip.frag -o pp_flip_frag.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/pp_blur.frag -o pp_blur_frag.spv
C:/VulkanSDK/1.3.224.1/Bin/glslc.exe shaders/pp_fxaa.frag -o pp_fxaa_frag.spv